spring.application.name=SafeWalk

##Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

api.prefix=/api/v1

spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}

app.anomaly.arrival-radius-meter=30
app.anomaly.auto-end-grace-period=300

app.google.maps.api-key=${GOOGLE_MAPS_API_KEY}

# Enable debug logging for the SafeWalk application
logging.level.com.samwallflower.safewalk=DEBUG


app.routing.segment-buffer-meters=300
app.routing.penalty-meters-per-severity-point=50

app.twilio.account-sid=${TWILIO_ACCOUNT_SID}
app.twilio.auth-token=${TWILIO_AUTH_TOKEN}
app.twilio.from-number=${TWILIO_FROM_NUMBER}

spring.config.import=optional:file:.env[.properties]

